/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/assessments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve a list of all assessments
         * @description Retrieves all assessments that have been created in the system.
         *     Useful for monitoring and managing multiple assessments in one place.
         *
         */
        get: operations["getAssessments"];
        put?: never;
        /**
         * Start a new assessment process
         * @description Initiates a new assessment for a given role.
         *     You can specify a role ARN for the assessment, or a default role will be used.
         *
         */
        post: operations["startAssessment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve details of a specific assessment
         * @description Retrieves detailed information about a specific assessment,
         *     including associated findings, questions, and any current errors.
         *
         */
        get: operations["getAssessment"];
        /**
         * Update the details of a specific assessment
         * @description Updates the details of a specific assessment, such as the name or role ARN.
         *
         */
        put: operations["updateAssessment"];
        /**
         * Rescan an assessment
         * @description Rescans an assessment, updating the findings and best practices.
         *
         */
        post: operations["rescanAssessment"];
        /**
         * Delete a specific assessment
         * @description Deletes an assessment from the system.
         *     Once deleted, the assessment cannot be recovered.
         *
         */
        delete: operations["deleteAssessment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessmentId}/milestones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve all milestones for a specific assessment
         * @description Fetches all milestones associated with a specific assessment.
         *
         */
        get: operations["getMilestones"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessmentId}/milestones/{milestoneId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve a specific milestone
         * @description Fetches all details associated with a specific milestone.
         *
         */
        get: operations["getMilestone"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessmentId}/exports/create-milestone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a milestone for the assessment
         * @description Creates a milestone for the assessment.
         *
         */
        post: operations["createMilestone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessmentId}/exports/well-architected-tool": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export the assessment to Well Architected Tool
         * @description Exports the assessment to Well Architected Tool.
         *
         */
        post: operations["exportWellArchitectedTool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessmentId}/exports/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the PDF exports of an assessment
         * @description Lists the PDF exports of an assessment.
         *
         */
        get: operations["listPDFExports"];
        put?: never;
        /**
         * Starts a PDF export for the specified assessment
         * @description Starts a PDF export for the specified assessment.
         *
         */
        post: operations["startPDFExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessmentId}/exports/pdf/{fileExportId}/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Generate a pre-signed URL for a specific PDF export of an assessment
         * @description Generates a pre-signed URL for a specific PDF export of an assessment.
         *
         */
        get: operations["generatePDFExportURL"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessmentId}/exports/pdf/{fileExportId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a specific PDF export of an assessment
         * @description Deletes a specific PDF export of an assessment.
         *
         */
        delete: operations["deletePDFExport"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessmentId}/pillars/{pillarId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update the details of a specific pillar
         * @description Updates the details of a specific pillar.
         *
         */
        put: operations["updatePillar"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessmentId}/pillars/{pillarId}/questions/{questionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update the details of a specific question
         * @description Updates the details of a specific question.
         *
         */
        put: operations["updateQuestion"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessmentId}/pillars/{pillarId}/questions/{questionId}/best-practices/{bestPracticeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve all findings for a specific best practice
         * @description Fetches all the findings associated with a specific best practice within a question in a given pillar for a specific assessment.
         *
         */
        get: operations["getBestPracticeFindings"];
        /**
         * Update the details of a specific best practice
         * @description Updates the details of a specific best practice.
         *
         */
        put: operations["updateBestPractice"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessmentId}/findings/{findingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve the details of a specific finding
         * @description Fetches detailed information about a specific finding related to an assessment,
         *     including severity, status, and recommended remediation steps.
         *
         */
        get: operations["getFinding"];
        /**
         * Update the details of a specific finding
         * @description Updates the details of a specific finding.
         *
         */
        put: operations["updateFinding"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessmentId}/findings/{findingId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a comment to a specific finding
         * @description Adds a comment to a specific finding.
         *
         */
        post: operations["addComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessmentId}/findings/{findingId}/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update the details of a specific comment
         * @description Updates the details of a specific comment.
         *
         */
        put: operations["updateComment"];
        post?: never;
        /**
         * Delete a specific comment
         * @description Deletes a specific comment.
         *
         */
        delete: operations["deleteComment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Assessment: {
            /** @description Unique identifier of the assessment */
            id?: string;
            /** @description Name or title of the assessment */
            name?: string;
            /** @description User who created the assessment */
            createdBy?: string;
            /** @description Organization associated with the assessment */
            organization?: string;
            /** @description List of regions to scan
             *     If empty, all regions will be scanned
             *      */
            regions?: string[];
            /** @description Region where the assessment is exported */
            exportRegion?: string;
            /** @description Role ARN associated with the assessment */
            roleArn?: string;
            /** @description Workflows associated with the assessment */
            workflows?: string[];
            /** @description ISO-formatted date when the assessment was created */
            createdAt?: string;
            /**
             * @description Current step in the assessment process
             * @enum {string}
             */
            step?: "SCANNING_STARTED" | "PREPARING_ASSOCIATIONS" | "ASSOCIATING_FINDINGS" | "FINISHED" | "ERRORED";
            error?: components["schemas"]["AssessmentError"];
        };
        AssessmentContent: components["schemas"]["Assessment"] & {
            /** @description The assessment pillars including questions and best practices */
            pillars?: components["schemas"]["Pillar"][];
            /** @description The version of questions that were used for the assessment */
            questionVersion?: string;
            /** @description Processed data from the scanning tools */
            graphData?: {
                /** @description Regions where findings were found */
                regions?: Record<string, unknown>;
                /** @description Resource types where findings were found */
                resourceTypes?: Record<string, unknown>;
                /** @description Severity levels where findings were found */
                severities?: Record<string, unknown>;
                /** @description Total number of findings */
                findings?: number;
            };
        };
        /** @description Error details if an issue occurred during the assessment process. */
        AssessmentError: {
            error?: string;
            cause?: string;
        } | null;
        AssessmentDto: {
            name?: string;
        };
        /** @description A finding within an assessment, providing details on the issue found */
        Finding: {
            /** @description Unique identifier of the finding */
            id?: string;
            /** @description Severity level of the finding (e.g., Low, Medium, High) */
            severity?: string;
            /** @description The status of the finding (e.g., MANUAL, FAIL) */
            statusCode?: string;
            /** @description Explanation or additional details about the finding's status */
            statusDetail?: string;
            /** @description Whether the finding is hidden or not */
            hidden?: boolean;
            /** @description List of resources related to the finding */
            resources?: {
                /** @description ARN or unique identifier of the resource */
                uid?: string | null;
                /** @description Name of the resource */
                name?: string | null;
                /** @description Type of resource (e.g., S3Bucket) */
                type?: string | null;
                /** @description The region or location of the resource */
                region?: string | null;
            }[];
            /** @description Remediation advice for resolving the issue found */
            remediation?: {
                /** @description Textual guidance on how to resolve the finding */
                desc?: string;
                /** @description List of resources (URLs, CLI commands) for remediation */
                references?: string[];
            };
            /** @description Explanation of the risk associated with the finding */
            riskDetails?: string;
            /** @description Tells whether the finding is associated with an AI or manually */
            isAIAssociated?: boolean;
            comments?: components["schemas"]["Comment"][];
        };
        FindingDto: {
            hidden?: boolean;
        };
        Comment: {
            /** @description Unique identifier of the comment */
            id: string;
            /** @description Id of the user who created the comment */
            authorId: string;
            /** @description Email of the user who created the comment */
            authorEmail?: string;
            /** @description Text of the comment */
            text: string;
            /**
             * Format: date-time
             * @description ISO-formatted date of when the comment was created
             */
            createdAt: string;
        };
        CommentDto: {
            /** @description Text of the comment */
            text: string;
        };
        Pillar: {
            id: string;
            label: string;
            disabled: boolean;
            questions: components["schemas"]["Question"][];
        };
        PillarDto: {
            disabled?: boolean;
        };
        Question: {
            id: string;
            label: string;
            none: boolean;
            disabled: boolean;
            bestPractices: components["schemas"]["BestPractice"][];
        };
        QuestionDto: {
            none?: boolean;
            disabled?: boolean;
        };
        /** @description A best practice related to a question and pillar in the assessment */
        BestPractice: {
            id: string;
            label: string;
            /** @enum {string} */
            risk: "Unknown" | "Informational" | "Low" | "Medium" | "High" | "Critical" | "Fatal" | "Other";
            description: string;
            checked: boolean;
            results: string[];
        };
        /** @description Enhanced best practice information, including associated findings */
        BestPracticeExtra: components["schemas"]["BestPractice"] & {
            results?: components["schemas"]["Finding"][];
        };
        BestPracticeDto: {
            checked?: boolean;
        };
        /** Milestone */
        Milestone: {
            id: number;
            name: string;
            /** Format: date-time */
            createdAt: string;
            pillars: components["schemas"]["Pillar"][];
        };
        /** MilestoneSummary */
        MilestoneSummary: {
            id: number;
            name: string;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description A file export related to an assessment */
        FileExport: {
            id: string;
            /** @enum {string} */
            status: "NOT_STARTED" | "IN_PROGRESS" | "COMPLETED" | "ERRORED";
            error?: string;
            versionName: string;
            createdAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAssessments: {
        parameters: {
            query?: {
                /** @description Maximum number of assessments to return */
                limit?: number;
                /** @description Search term to filter assessments by name, role ARN, or id */
                search?: string;
                /** @description Token for pagination. */
                nextToken?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of all assessments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        assessments?: components["schemas"]["Assessment"][];
                        /** @description Token for pagination. If there are more assessments than can be returned in a single response,
                         *     this token will allow you to retrieve the next set of results.
                         *      */
                        nextToken?: string;
                    };
                };
            };
            /** @description A issue occurred while trying to retrieve the organization of the user */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    startAssessment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Name of the assessment to be created */
                    name: string;
                    /** @description List of regions to scan
                     *     If empty, all regions will be scanned
                     *      */
                    regions?: string[];
                    /** @description The role ARN to associate with the assessment.
                     *     If not provided, a default role will be used.
                     *      */
                    roleArn: string;
                    /** @description The workflows to associate with the assessment.
                     *     If not provided, no workflows will be associated.
                     *      */
                    workflows?: string[];
                };
            };
        };
        responses: {
            /** @description The assessment has been successfully created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description The unique ID of the newly created assessment */
                        assessmentId?: string;
                    };
                };
            };
            /** @description Bad Request. Missing or invalid parameters were provided. Or a issue occurred while trying to retrieve the organization of the user or the user id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Payment Required. The user does not have a subscription */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAssessment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique ID of the assessment to retrieve */
                assessmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detailed information about the specified assessment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentContent"];
                };
            };
            /** @description The specified assessment could not be found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateAssessment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique ID of the assessment to update */
                assessmentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssessmentDto"];
            };
        };
        responses: {
            /** @description The assessment has been successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request or empty body or a issue occurred while trying to retrieve the organization of the user */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The specified assessment could not be found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rescanAssessment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique ID of the assessment to rescan */
                assessmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The assessment has been successfully rescanned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A issue occurred while trying to retrieve the organization of the user */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The specified assessment could not be found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteAssessment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique ID of the assessment to delete */
                assessmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The assessment has been successfully deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A issue occurred while trying to retrieve the organization of the user */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The specified assessment could not be found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMilestones: {
        parameters: {
            query?: {
                /** @description The region to filter milestones by. */
                region?: string;
                /** @description Maximum number of milestones to return */
                limit?: number;
                /** @description Token for pagination. */
                nextToken?: string;
            };
            header?: never;
            path: {
                /** @description The unique ID of the assessment to retrieve milestones for */
                assessmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of milestones related to the specified assessment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        milestones: components["schemas"]["MilestoneSummary"][];
                        /** @description Token for pagination. If there are more milestones than can be returned in a single response,
                         *     this token will allow you to retrieve the next set of results.
                         *      */
                        nextToken?: string;
                    };
                };
            };
            /** @description An issue occurred while trying to retrieve the organization of the user */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The specified assessment could not be found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMilestone: {
        parameters: {
            query?: {
                /** @description The region to filter milestones by. */
                region?: string;
            };
            header?: never;
            path: {
                /** @description The unique ID of the assessment to retrieve milestones for */
                assessmentId: string;
                /** @description The unique ID of the milestone to retrieve pillars for */
                milestoneId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of pillars related to the specified milestone */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Milestone"];
                };
            };
            /** @description An issue occurred while trying to retrieve the organization of the user */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The specified assessment could not be found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createMilestone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique ID of the assessment to create a milestone for */
                assessmentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description The region to create the milestone in. */
                    region?: string;
                    /** @description The name of the milestone to create. */
                    name: string;
                };
            };
        };
        responses: {
            /** @description The milestone has been successfully created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request body or a issue occurred while trying to retrieve the organization or email of the user */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The specified assessment could not be found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    exportWellArchitectedTool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique ID of the assessment to export */
                assessmentId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description The region to export the assessment to. */
                    region?: string;
                };
            };
        };
        responses: {
            /** @description The assessment has been successfully exported */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request body or a issue occurred while trying to retrieve the organization or email of the user */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The specified assessment could not be found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listPDFExports: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique ID of the assessment to list the exports of */
                assessmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The list of PDF exports has been successfully retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileExport"][];
                };
            };
            /** @description Invalid request path parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The specified assessment could not be found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    startPDFExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique ID of the assessment to export */
                assessmentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description The version name of the PDF export */
                    versionName: string;
                };
            };
        };
        responses: {
            /** @description The PDF export has been started successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The specified assessment could not be found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    generatePDFExportURL: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique ID of the assessment to list the exports of */
                assessmentId: string;
                /** @description The unique ID of the PDF export to delete */
                fileExportId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The PDF export URL has been successfully generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description The URL of the PDF export */
                        url: string;
                    };
                };
            };
            /** @description Invalid request path parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The specified assessment could not be found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deletePDFExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique ID of the assessment to list the exports of */
                assessmentId: string;
                /** @description The unique ID of the PDF export to delete */
                fileExportId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The PDF export has been successfully deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request path parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The specified assessment could not be found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updatePillar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the assessment */
                assessmentId: string;
                /** @description The ID of the pillar */
                pillarId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PillarDto"];
            };
        };
        responses: {
            /** @description The pillar has been successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request body or a issue occurred while trying to retrieve the organization of the user */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The specified assessment, or pillar could not be found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the assessment */
                assessmentId: string;
                /** @description The ID of the pillar under which the question falls */
                pillarId: string;
                /** @description The ID of the question */
                questionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionDto"];
            };
        };
        responses: {
            /** @description The question has been successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request body or a issue occurred while trying to retrieve the organization of the user */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The specified assessment, pillar, or question could not be found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getBestPracticeFindings: {
        parameters: {
            query?: {
                /** @description Maximum number of assessments to return */
                limit?: number;
                /** @description Search term to filter assessments by name, role ARN, or id */
                search?: string;
                /** @description Show hidden findings */
                showHidden?: boolean;
                /** @description Token for pagination. */
                nextToken?: string;
            };
            header?: never;
            path: {
                /** @description The ID of the assessment */
                assessmentId: string;
                /** @description The ID of the pillar under which the question falls */
                pillarId: string;
                /** @description The ID of the question to retrieve the best practices to */
                questionId: string;
                /** @description The ID of the best practice to retrieve findings to */
                bestPracticeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of findings related to the specified best practice */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["Finding"][];
                        /** @description Token for pagination. If there are more findings than can be returned in a single response,
                         *     this token will allow you to retrieve the next set of results.
                         *      */
                        nextToken?: string;
                    };
                };
            };
            /** @description A issue occurred while trying to retrieve the organization of the user */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The specified best practice could not be found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateBestPractice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the assessment */
                assessmentId: string;
                /** @description The ID of the pillar under which the question falls */
                pillarId: string;
                /** @description The ID of the question to update the best practice to */
                questionId: string;
                /** @description The ID of the best practice */
                bestPracticeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BestPracticeDto"];
            };
        };
        responses: {
            /** @description The best practice has been successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid or empty request body or a issue occurred while trying to retrieve the organization of the user */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The specified assessment, pillar, question, or best practice could not be found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getFinding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the assessment to which the finding belongs */
                assessmentId: string;
                /** @description The unique ID of the finding to retrieve */
                findingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detailed information about the specified finding */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Finding"];
                };
            };
            /** @description A issue occurred while trying to retrieve the organization of the user */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The specified assessment or finding could not be found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateFinding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the assessment to which the finding belongs */
                assessmentId: string;
                /** @description The unique ID of the finding to retrieve */
                findingId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindingDto"];
            };
        };
        responses: {
            /** @description The finding has been successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request or empty body or a issue occurred while trying to retrieve the organization of the user */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The specified assessment could not be found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    addComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the assessment to which the finding belongs */
                assessmentId: string;
                /** @description The unique ID of the finding to add a comment to */
                findingId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Text of the comment */
                    text: string;
                };
            };
        };
        responses: {
            /** @description The comment has been successfully added */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            /** @description Invalid request body or a issue occurred while trying to retrieve the organization of the user */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The specified assessment or finding could not be found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the assessment to which the finding belongs */
                assessmentId: string;
                /** @description The unique ID of the finding to which the comment belongs */
                findingId: string;
                /** @description The unique ID of the comment to update */
                commentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentDto"];
            };
        };
        responses: {
            /** @description The comment has been successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request body or a issue occurred while trying to retrieve the organization of the user */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The specified assessment, finding, or comment could not be found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the assessment to which the finding belongs */
                assessmentId: string;
                /** @description The unique ID of the finding to which the comment belongs */
                findingId: string;
                /** @description The unique ID of the comment to delete */
                commentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The comment has been successfully deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A issue occurred while trying to retrieve the organization of the user */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
