AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: wafr-automation-tool

Parameters:
  Owner:
    Type: String
    Default: Antoine Berger
  Project:
    Type: String
    Default: WAFR Automation Tool
  Name:
    Type: String
    Default: wafr-automation-tool
  Debug:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

Resources:
  SharedLibs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "${AWS::StackName}-SharedLibs"
      Description: Shared libs used by Lambdas
      ContentUri: ./backend/src/shared_lib
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.12
  Api:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./infrastructure/api.yaml
      Tags:
        Owner: !Ref Owner
        Project: !Ref Project
        Name: !Ref Name
      Parameters:
        StateMachineArn: !GetAtt StateMachine.Outputs.StateMachineArn
        DynamoDBArn: !GetAtt DynamoDB.Arn
        SharedLibsLayer: !Ref SharedLibs
        DefaultAssessmentRole: !GetAtt ScanningTools.Outputs.DefaultAssessmentRole
  Network:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./infrastructure/network.yaml
      Tags:
        Owner: !Ref Owner
        Project: !Ref Project
        Name: !Ref Name
  ScanningTools:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./infrastructure/scanning-tools.yaml
      Tags:
        Owner: !Ref Owner
        Project: !Ref Project
        Name: !Ref Name
      Parameters:
        ParentStackName: !Ref "AWS::StackName"
        S3BucketName: !Ref S3Bucket
  StateMachine:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./infrastructure/state-machine.yaml
      Tags:
        Owner: !Ref Owner
        Project: !Ref Project
        Name: !Ref Name
      Parameters:
        ParentStackName: !Ref "AWS::StackName"
        Debug: !Ref Debug
        SharedLibsLayer: !Ref SharedLibs
        DynamoDBArn: !GetAtt DynamoDB.Arn
        S3BucketName: !Ref S3Bucket
        ECSCluster: !GetAtt ScanningTools.Outputs.ECSCluster
        ECSExecutionRole: !GetAtt ScanningTools.Outputs.ECSExecutionRole
        ProwlerTaskDefinition: !GetAtt ScanningTools.Outputs.ProwlerTaskDefinition
        ProwlerTaskRole: !GetAtt ScanningTools.Outputs.ProwlerTaskRole
        CloudCustodianTaskDefinition: !GetAtt ScanningTools.Outputs.CloudCustodianTaskDefinition
        CloudCustodianTaskRole: !GetAtt ScanningTools.Outputs.CloudCustodianTaskRole
        Subnet: !GetAtt Network.Outputs.Subnet
        SecurityGroup: !GetAtt Network.Outputs.SecurityGroup
  DynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner
        - Key: Name
          Value: !Ref Name
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-${AWS::AccountId}"
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner
        - Key: Name
          Value: !Ref Name
