AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: wafr-automation-tool

Parameters:
  Owner:
    Type: String
  Project:
    Type: String
    Default: wafr-automation-tool
  Debug:
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
  InitialUserEmail:
    Type: String
  LogRetentionInDays:
    Type: Number
    Default: 14
  UnitBasedPricingProductCode:
    Type: String
    Default: ''
  MonthlySubscriptionProductCode:
    Type: String
    Default: ''
  GenAIMaxRetries:
    Type: Number
    Default: 3
  AIFindingsAssociationChunkSize:
    Type: Number
    Default: 10

Resources:
  Api:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./infrastructure/api.yaml
      Tags:
        Owner: !Ref Owner
        Project: !Ref Project
        Name: API
      Parameters:
        Owner: !Ref Owner
        Project: !Ref Project
        StateMachineArn: !GetAtt StateMachine.Outputs.StateMachineArn
        StateMachineName:
          !Select [
            6,
            !Split [':', !GetAtt StateMachine.Outputs.StateMachineArn],
          ]
        DynamoDBArn: !GetAtt DynamoDB.Arn
        DefaultAssessmentRole: !GetAtt ScanningTools.Outputs.DefaultAssessmentRole
        InitialUserEmail: !Ref InitialUserEmail
        LogRetentionInDays: !Ref LogRetentionInDays
        OrganizationTableArn: !GetAtt OrganizationTable.Arn
        UnitBasedPricingProductCode: !Ref UnitBasedPricingProductCode
        MonthlySubscriptionProductCode: !Ref MonthlySubscriptionProductCode
  Network:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./infrastructure/network.yaml
      Tags:
        Owner: !Ref Owner
        Project: !Ref Project
        Name: Network
      Parameters:
        Owner: !Ref Owner
        Project: !Ref Project
  ScanningTools:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./infrastructure/scanning-tools.yaml
      Tags:
        Owner: !Ref Owner
        Project: !Ref Project
        Name: Scanning Tools
      Parameters:
        Owner: !Ref Owner
        Project: !Ref Project
        ParentStackName: !Ref 'AWS::StackName'
        S3BucketName: !Ref S3Bucket
        LogRetentionInDays: !Ref LogRetentionInDays
  StateMachine:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./infrastructure/state-machine.yaml
      Tags:
        Owner: !Ref Owner
        Project: !Ref Project
        Name: State Machine
      Parameters:
        Owner: !Ref Owner
        Project: !Ref Project
        ParentStackName: !Ref 'AWS::StackName'
        Debug: !Ref Debug
        DynamoDBArn: !GetAtt DynamoDB.Arn
        S3BucketName: !Ref S3Bucket
        ECSCluster: !GetAtt ScanningTools.Outputs.ECSCluster
        ECSExecutionRole: !GetAtt ScanningTools.Outputs.ECSExecutionRole
        ProwlerTaskDefinition: !GetAtt ScanningTools.Outputs.ProwlerTaskDefinition
        ProwlerTaskRole: !GetAtt ScanningTools.Outputs.ProwlerTaskRole
        CloudCustodianTaskDefinition: !GetAtt ScanningTools.Outputs.CloudCustodianTaskDefinition
        CloudCustodianTaskRole: !GetAtt ScanningTools.Outputs.CloudCustodianTaskRole
        CloudSploitTaskDefinition: !GetAtt ScanningTools.Outputs.CloudSploitTaskDefinition
        CloudSploitTaskRole: !GetAtt ScanningTools.Outputs.CloudSploitTaskRole
        Subnet: !GetAtt Network.Outputs.Subnet
        SecurityGroup: !GetAtt Network.Outputs.SecurityGroup
        LogRetentionInDays: !Ref LogRetentionInDays
        OrganizationTableArn: !GetAtt OrganizationTable.Arn
        UnitBasedPricingProductCode: !Ref UnitBasedPricingProductCode
        MonthlySubscriptionProductCode: !Ref MonthlySubscriptionProductCode
        GenAIMaxRetries: !Ref GenAIMaxRetries
        AIFindingsAssociationChunkSize: !Ref AIFindingsAssociationChunkSize
  DynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref AWS::StackName
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner
        - Key: Name
          Value: DynamoDB
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      DeletionProtectionEnabled: true
  OrganizationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-organization'
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner
        - Key: Name
          Value: OrganizationTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
      DeletionProtectionEnabled: true
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-${AWS::AccountId}'
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner
        - Key: Name
          Value: S3 Bucket
  Frontend:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./infrastructure/frontend.yaml
      Tags:
        Owner: !Ref Owner
        Project: !Ref Project
        Name: Frontend
      Parameters:
        Owner: !Ref Owner
        Project: !Ref Project
        ParentStackName: !Ref AWS::StackName

Outputs:
  ApiEndpoint:
    Description: API Endpoint
    Value: !GetAtt Api.Outputs.ApiEndpoint
  CognitoUserPoolId:
    Description: User Pool ID
    Value: !GetAtt Api.Outputs.UserPoolId
  CognitoUserPoolClientId:
    Description: User Pool Client ID
    Value: !GetAtt Api.Outputs.UserPoolClientId
  CognitoIdentityPoolId:
    Description: Identity Pool ID
    Value: !GetAtt Api.Outputs.IdentityPoolId
  CloudFrontS3BucketName:
    Description: CloudFront S3 Bucket Name
    Value: !GetAtt Frontend.Outputs.S3BucketName
  CloudFrontDistributionId:
    Description: CloudFront Distribution ID
    Value: !GetAtt Frontend.Outputs.DistributionId
