/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/assessments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve a list of all assessments
         * @description Retrieves all assessments that have been created in the system.
         *     Useful for monitoring and managing multiple assessments in one place.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of all assessments */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            assessments?: components["schemas"]["Assessment"][];
                            /** @description Token for pagination. If there are more assessments than can be returned in a single response,
                             *     this token will allow you to retrieve the next set of results.
                             *      */
                            next_token?: string;
                        };
                    };
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Start a new assessment process
         * @description Initiates a new assessment for a given role.
         *     You can specify a role ARN for the assessment, or a default role will be used.
         *
         */
        post: {
            parameters: {
                query: {
                    /** @description Name of the assessment to be created */
                    name: string;
                    /** @description The role ARN to associate with the assessment.
                     *     If not provided, a default role will be used.
                     *      */
                    roleArn?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The assessment has been successfully created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The unique ID of the newly created assessment */
                            assessmentId?: number;
                        };
                    };
                };
                /** @description Bad Request. Missing or invalid parameters were provided. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve details of a specific assessment
         * @description Retrieves detailed information about a specific assessment,
         *     including associated findings, questions, and any current errors.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The unique ID of the assessment to retrieve */
                    assessmentId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Detailed information about the specified assessment */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssessmentContent"];
                    };
                };
                /** @description The specified assessment could not be found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete a specific assessment
         * @description Deletes an assessment from the system.
         *     Once deleted, the assessment cannot be recovered.
         *
         */
        delete: operations["deleteAssessment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessmentId}/pillars/{pillarId}/questions/{questionId}/best-practices/{bestPracticeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve all findings for a specific best practice
         * @description Fetches all the findings associated with a specific best practice within a question in a given pillar for a specific assessment.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The ID of the assessment */
                    assessmentId: number;
                    /** @description The ID of the pillar under which the question falls */
                    pillarId: number;
                    /** @description The ID of the question to retrieve the best practices to */
                    questionId: number;
                    /** @description The ID of the best practice to retrieve findings to */
                    bestPracticeId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of findings related to the specified best practice */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BestPracticeExtra"];
                    };
                };
                /** @description The specified best practice could not be found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessmentId}/pillars/{pillarId}/questions/{questionId}/best-practices/{bestPracticeId}/{status}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update the status of a specific best practice
         * @description Updates the status of a best practice for a given question in the assessment
         *
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The ID of the assessment */
                    assessmentId: number;
                    /** @description The ID of the pillar under which the question falls */
                    pillarId: number;
                    /** @description The ID of the question to update the best practice to */
                    questionId: number;
                    /** @description The ID of the best practice to update the status to */
                    bestPracticeId: string;
                    /** @description The status to set for the best practice */
                    status: boolean;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The status of the best practice was successfully updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The specified assessment, pillar, question, or best practice could not be found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessmentId}/findings/{findingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve the details of a specific finding
         * @description Fetches detailed information about a specific finding related to an assessment,
         *     including severity, status, and recommended remediation steps.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The ID of the assessment to which the finding belongs */
                    assessmentId: number;
                    /** @description The unique ID of the finding to retrieve */
                    findingId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Detailed information about the specified finding */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Finding"];
                    };
                };
                /** @description The specified assessment or finding could not be found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Assessment: {
            /** @description Unique identifier of the assessment */
            id?: string;
            /** @description Name or title of the assessment */
            name?: string;
            /** @description Role ARN associated with the assessment */
            role_arn?: string;
            /** @description ISO-formatted date when the assessment was created */
            created_at?: string;
            /**
             * @description Current step in the assessment process
             * @enum {string}
             */
            step?: "SCANNING_STARTED" | "PREPARING_PROMPTS" | "INVOKING_LLM" | "FINISHED" | "ERRORED";
            error?: components["schemas"]["AssessmentError"];
            /** @description The version of questions that were used for the assessment */
            question_version?: string;
        };
        AssessmentContent: components["schemas"]["Assessment"] & {
            /** @description A list of findings associated with the assessment */
            findings?: components["schemas"]["Pillar"][];
        };
        /** @description Error details if an issue occurred during the assessment process. */
        AssessmentError: {
            Error?: string;
            Cause?: string;
        } | null;
        /** @description A finding within an assessment, providing details on the issue found */
        Finding: {
            /** @description Unique identifier of the finding */
            id?: number;
            /** @description Severity level of the finding (e.g., Low, Medium, High) */
            severity?: string;
            /** @description The status of the finding (e.g., MANUAL, FAIL) */
            status_code?: string;
            /** @description Explanation or additional details about the finding's status */
            status_detail?: string;
            /** @description List of resources related to the finding */
            resources?: {
                /** @description ARN or unique identifier of the resource */
                uid?: string;
                /** @description Name of the resource */
                name?: string;
                /** @description Type of resource (e.g., S3Bucket) */
                type?: string;
                /** @description The region or location of the resource */
                region?: string;
            }[];
            /** @description Remediation advice for resolving the issue found */
            remediation?: {
                /** @description Textual guidance on how to resolve the finding */
                desc?: string;
                /** @description List of resources (URLs, CLI commands) for remediation */
                references?: string[];
            };
            /** @description Explanation of the risk associated with the finding */
            risk_details?: string;
        };
        Pillar: {
            id?: string;
            label?: string;
            questions?: components["schemas"]["Question"][];
        };
        Question: {
            id?: string;
            label?: string;
            best_practices?: components["schemas"]["BestPractice"][];
        };
        /** @description A best practice related to a question and pillar in the assessment */
        BestPractice: {
            id?: string;
            label?: string;
            /** @enum {string} */
            risk?: "High" | "Medium" | "Low";
            status?: boolean;
            results?: string[];
        };
        /** @description Enhanced best practice information, including associated findings */
        BestPracticeExtra: components["schemas"]["BestPractice"] & {
            results?: components["schemas"]["Finding"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    deleteAssessment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique ID of the assessment to delete */
                assessmentId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The assessment has been successfully deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The specified assessment could not be found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
