/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/assessments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve all assessments */
        get: operations["getAllAssessments"];
        put?: never;
        /**
         * Start a new assessment
         * @description Initiates a new assessment process for the specified role.
         */
        post: operations["startAssessment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve details of a specific assessment */
        get: operations["getAssessment"];
        put?: never;
        post?: never;
        /** Delete an assessment */
        delete: operations["deleteAssessment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessmentId}/best-practices/{bestPracticeName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve all findings for a specific best pratice */
        get: operations["getAllFindingsByBestPractice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessmentId}/best-practices/{bestPracticeName}/{status}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Retrieve all findings for a specific best pratice */
        put: operations["getAllFindingsByBestPractice2"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessmentId}/findings/{findingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve the details of a specific finding */
        get: operations["getFindingById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Assessment: {
            /** @description Unique ID of the assessment */
            id?: string;
            /** @description Name of the assessment */
            name?: string;
            /** @description Role associated with the assessment */
            role?: string;
            /** @description Current step of the assessment */
            step?: string;
            error?: components["schemas"]["AssessmentError"];
            /** @description The version of questions used */
            question_version?: string;
        };
        AssessmentContent: {
            /** @description Unique ID of the assessment */
            id?: string;
            /** @description Name of the assessment */
            name?: string;
            /** @description Role associated with the assessment */
            role_arn?: string;
            /**
             * @description Current step of the assessment
             * @enum {string}
             */
            step?: "SCANNING_STARTED" | "PREPARING_PROMPTS" | "INVOKING_LLM" | "FINISHED" | "ERRORED";
            /** @description The version of questions used */
            question_version?: string | null;
            /** @description JSONObject containing each pillar */
            findings?: {
                /** @description JSONObject containing questions for each pillar */
                pillars?: {
                    /** @description JSONObject containing best practices for each question */
                    questions?: {
                        best_practices?: components["schemas"]["BestPractice"];
                    };
                };
            };
        };
        /** @description Present if an error has occurred during the process. */
        AssessmentError: {
            Error?: string;
            Cause?: string;
        } | null;
        /** @description Finding definition */
        Finding: {
            /** @description Finding id */
            id?: number;
            /** @description Textual severity (e.g., Low, Medium, High) */
            severity?: string;
            /** @description Short status code (e.g., PASS, FAIL) */
            status_code?: string;
            /** @description Explanation for the status */
            status_detail?: string;
            /** @description List of resources associated with the finding */
            resources?: {
                /** @description ARN or unique ID of the resource */
                uid?: string;
                /** @description Resource name */
                name?: string;
                /** @description Simple resource type (e.g., Other, S3Bucket) */
                type?: string;
                /** @description AWS region or other location */
                region?: string;
            }[];
            /** @description Recommended steps for remediation */
            remediation?: {
                /** @description Textual remediation guidance */
                desc?: string;
                /** @description List of URLs or CLI commands */
                references?: string[];
            };
            /** @description Explanation of the security risk or reason for the finding */
            risk_details?: string;
        };
        /** @description Best practice object */
        BestPractice: {
            /** @enum {string} */
            risk?: "High" | "Medium" | "Low";
            status?: boolean;
            results?: string[];
        };
        /** @description Best practice object with finding content */
        BestPracticeExtra: {
            /** @enum {string} */
            risk?: "High" | "Medium" | "Low";
            status?: boolean;
            results?: components["schemas"]["Finding"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAllAssessments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of all assessments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        assessments?: components["schemas"]["Assessment"][];
                        next_token?: string;
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    startAssessment: {
        parameters: {
            query: {
                /** @description Name of the assessment */
                name: string;
                /** @description Role for which to start the assessment \
                 *     If not set a default role will be used
                 *      */
                roleArn?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Assessment successfully created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description The created assessment ID */
                        assessmentId?: number;
                    };
                };
            };
            /** @description Missing or invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAssessment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the assessment to retrieve */
                assessmentId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Assessment details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentContent"];
                };
            };
            /** @description Assessment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteAssessment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the assessment to delete */
                assessmentId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Assessment successfully deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Assessment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAllFindingsByBestPractice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the assessment */
                assessmentId: number;
                /** @description The name of the best practice */
                bestPracticeName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of finding for the specific best practice */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BestPracticeExtra"];
                };
            };
            /** @description Best practice not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAllFindingsByBestPractice2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the assessment */
                assessmentId: number;
                /** @description The name of the best practice */
                bestPracticeName: string;
                status: boolean;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of finding for the specific best practice */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BestPracticeExtra"];
                };
            };
            /** @description Best practice not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getFindingById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the assessment */
                assessmentId: number;
                /** @description The ID of the finding */
                findingId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Details of the finding */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Finding"];
                };
            };
            /** @description Assessment or finding not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
