AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: API Lambda Functions

Parameters:
  Owner:
    Type: String
    Default: Antoine Berger
  Project:
    Type: String
    Default: WAFR Automation Tool
  Name:
    Type: String
    Default: api
  StateMachineArn:
    Type: String
  DynamoDBArn:
    Type: String
  SharedLibsLayer:
    Type: String
  DefaultAssessmentRole:
    Type: String
  InitialUserEmail:
    Type: String

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: python3.12
    Layers:
      - !Ref SharedLibsLayer
    Tags:
      Project: !Ref Project
      Owner: !Ref Owner
      Name: !Ref Name
    Environment:
      Variables:
        REGION: !Ref AWS::Region
        DDB_TABLE: !Ref DynamoDBArn
        STATE_MACHINE_ARN: !Ref StateMachineArn

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${AWS::StackName}"
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      Policies:
        PasswordPolicy:
          MinimumLength: 12
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: true
          StringAttributeConstraints:
            MaxLength: 320
            MinLength: 3
  UserPoolUser:
    Type: AWS::Cognito::UserPoolUser
    Properties:
      DesiredDeliveryMediums:
        - EMAIL
      UserAttributes:
        - Name: email
          Value: !Ref InitialUserEmail
        - Name: email_verified
          Value: true
      Username: !Ref InitialUserEmail
      UserPoolId: !Ref UserPool
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "${AWS::StackName}"
      UserPoolId: !Ref UserPool
      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      CallbackURLs:
        - !Sub "http://localhost:4000/auth_callback"
      SupportedIdentityProviders:
        - COGNITO
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlows:
        - code
  IdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: !Sub "${AWS::StackName}"
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId:
            Ref: UserPoolClient
          ProviderName:
            Fn::GetAtt:
              - UserPool
              - ProviderName
  CognitoAuthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud: !Ref IdentityPool
              "ForAnyValue:StringLike":
                cognito-identity.amazonaws.com:amr: authenticated
  IdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref IdentityPool
      Roles:
        authenticated: !GetAtt CognitoAuthenticatedRole.Arn
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'*'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt UserPool.Arn
      Tags:
        Owner: !Ref Owner
        Project: !Ref Project
        Name: !Ref Name

  StartAssessmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.12
      CodeUri: ../backend/src/api/start_assessment/app
      Environment:
        Variables:
          DEFAULT_ASSESSMENT_ROLE: !Ref DefaultAssessmentRole
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: states:StartExecution
              Resource: !Ref StateMachineArn
      Events:
        StartAssessment:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /assessments
            Method: POST
  RetrieveAllAssessmentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.12
      CodeUri: ../backend/src/api/retrieve_all_assessments/app
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:Query
              Resource: !Ref DynamoDBArn
      Events:
        RetrieveBestPractice:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /assessments
            Method: GET
  RetrieveAssessmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.12
      CodeUri: ../backend/src/api/retrieve_assessment/app
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource: !Ref DynamoDBArn
      Events:
        RetrieveProcessStep:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /assessments/{assessmentId}
            Method: GET
  DeleteAssessmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.12
      CodeUri: ../backend/src/api/delete_assessment/app
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - states:StopExecution
              Resource: !Join
                - ""
                - - "arn:aws:states:"
                  - !Ref "AWS::Region"
                  - ":"
                  - !Ref "AWS::AccountId"
                  - ":execution:"
                  - !Select [6, !Split [":", !Ref StateMachineArn]]
                  - ":*"
            - Effect: Allow
              Action:
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:GetItem
                - dynamodb:BatchWriteItem
              Resource: !Ref DynamoDBArn
      Events:
        DeleteAssessment:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /assessments/{assessmentId}
            Method: DELETE
  UpdateAssessmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.12
      CodeUri: ../backend/src/api/update_assessment/app
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
              Resource: !Ref DynamoDBArn
      Events:
        UpdateAssessment:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /assessments/{assessmentId}
            Method: PUT
  RescanAssessmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.12
      CodeUri: ../backend/src/api/rescan_assessment/app
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DeleteItem
                - dynamodb:GetItem
                - dynamodb:BatchWriteItem
                - dynamodb:Query
              Resource: !Ref DynamoDBArn
            - Effect: Allow
              Action: states:StartExecution
              Resource: !Ref StateMachineArn
      Events:
        RescanAssessment:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /assessments/{assessmentId}
            Method: POST
  UpdatePillarFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.12
      CodeUri: ../backend/src/api/update_pillar/app
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:UpdateItem
              Resource: !Ref DynamoDBArn
      Events:
        UpdatePillar:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /assessments/{assessmentId}/pillars/{pillarId}
            Method: PUT
  UpdateQuestionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.12
      CodeUri: ../backend/src/api/update_question/app
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:UpdateItem
              Resource: !Ref DynamoDBArn
      Events:
        UpdateQuestion:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /assessments/{assessmentId}/pillars/{pillarId}/questions/{questionId}
            Method: PUT
  RetrieveBestPracticeFindingsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.12
      CodeUri: ../backend/src/api/retrieve_best_practice_findings/app
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:BatchGetItem
              Resource: !Ref DynamoDBArn
      Events:
        RetrieveBestPracticeFindings:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /assessments/{assessmentId}/pillars/{pillarId}/questions/{questionId}/best-practices/{bestPracticeId}
            Method: GET
  UpdateBestPracticeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.12
      CodeUri: ../backend/src/api/update_best_practice/app
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:UpdateItem
              Resource: !Ref DynamoDBArn
      Events:
        UpdateBestPractice:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /assessments/{assessmentId}/pillars/{pillarId}/questions/{questionId}/best-practices/{bestPracticeId}
            Method: PUT
  RetrieveFindingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.12
      CodeUri: ../backend/src/api/retrieve_finding/app
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource: !Ref DynamoDBArn
      Events:
        RetrieveFinding:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /assessments/{assessmentId}/findings/{findingId}
            Method: GET
  UpdateFindingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.12
      CodeUri: ../backend/src/api/update_finding/app
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:UpdateItem
              Resource: !Ref DynamoDBArn
      Events:
        UpdateFinding:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /assessments/{assessmentId}/pillars/{pillarId}/questions/{questionId}/best-practices/{bestPracticeId}/findings/{findingId}
            Method: PUT

Outputs:
  ApiEndpoint:
    Description: API Endpoint
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/${Api.Stage}"
  UserPoolId:
    Description: User Pool ID
    Value: !Ref UserPool
  IdentityPoolId:
    Description: Identity Pool ID
    Value: !Ref IdentityPool
  UserPoolClientId:
    Description: User Pool Client ID
    Value: !Ref UserPoolClient
