AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: API Lambda Functions

Parameters:
  Owner:
    Type: String
    Default: Antoine Berger
  Project:
    Type: String
    Default: WAFR Automation Tool
  Name:
    Type: String
    Default: wafr-automation-tool
  StateMachineArn:
    Type: String
  DynamoDBArn:
    Type: String
  SharedLibsLayer:
    Type: String

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: python3.12
    Layers:
      - !Ref SharedLibsLayer
    Tags:
      Project: !Ref Project
      Owner: !Ref Owner
      Name: !Ref Name
    Environment:
      Variables:
        DDB_TABLE: !Ref DynamoDBArn
        STATE_MACHINE_ARN: !Ref StateMachineArn

Resources:
  DefaultAssessmentRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: ECSTaskPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: AllowMoreReadOnly
                Effect: Allow
                Action:
                  - account:Get*
                  - appstream:Describe*
                  - appstream:List*
                  - backup:List*
                  - backup:Get*
                  - bedrock:List*
                  - bedrock:Get*
                  - cloudtrail:GetInsightSelectors
                  - codeartifact:List*
                  - codebuild:BatchGet*
                  - codebuild:ListReportGroups
                  - cognito-idp:GetUserPoolMfaConfig
                  - dlm:Get*
                  - drs:Describe*
                  - ds:Get*
                  - ds:Describe*
                  - ds:List*
                  - dynamodb:GetResourcePolicy
                  - ec2:GetEbsEncryptionByDefault
                  - ec2:GetSnapshotBlockPublicAccessState
                  - ec2:GetInstanceMetadataDefaults
                  - ecr:Describe*
                  - ecr:GetRegistryScanningConfiguration
                  - elasticfilesystem:DescribeBackupPolicy
                  - glue:GetConnections
                  - glue:GetSecurityConfiguration*
                  - glue:SearchTables
                  - glue:GetMLTransforms
                  - lambda:GetFunction*
                  - logs:FilterLogEvents
                  - lightsail:GetRelationalDatabases
                  - macie2:GetMacieSession
                  - macie2:GetAutomatedDiscoveryConfiguration
                  - s3:GetAccountPublicAccessBlock
                  - shield:DescribeProtection
                  - shield:GetSubscriptionState
                  - securityhub:BatchImportFindings
                  - securityhub:GetFindings
                  - servicecatalog:Describe*
                  - servicecatalog:List*
                  - ssm:GetDocument
                  - ssm-incidents:List*
                  - states:ListTagsForResource
                  - support:Describe*
                  - tag:GetTagKeys
                  - wellarchitected:List*
                Resource: "*"
              - Sid: AllowAPIGatewayReadOnly
                Effect: Allow
                Action:
                  - apigateway:GET
                Resource:
                  - arn:aws:apigateway:::*/restapis/*
                  - arn:aws:apigateway:::*/apis/*
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
        - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Tags:
        Owner: !Ref Owner
        Project: !Ref Project
        Name: !Ref Name
      StageName: prod
      Cors: "'*'"
  StartAssessmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.12
      CodeUri: ../backend/src/api/start_assessment/app
      Environment:
        Variables:
          DEFAULT_ASSESSMENT_ROLE: !Ref DefaultAssessmentRole
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: states:StartExecution
              Resource: !Ref StateMachineArn
      Events:
        StartAssessment:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /assessments
            Method: POST
  RetrieveAllAssessmentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.12
      CodeUri: ../backend/src/api/retrieve_all_assessments/app
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:Query
              Resource: !Ref DynamoDBArn
      Events:
        RetrieveBestPractice:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /assessments
            Method: GET
  RetrieveAssessmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.12
      CodeUri: ../backend/src/api/retrieve_assessment/app
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource: !Ref DynamoDBArn
      Events:
        RetrieveProcessStep:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /assessments/{assessmentId}
            Method: GET
  DeleteAssessmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.12
      CodeUri: ../backend/src/api/delete_assessment/app
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - states:StopExecution
              Resource: !Ref StateMachineArn
            - Effect: Allow
              Action:
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:BatchWriteItem
              Resource: !Ref DynamoDBArn
      Events:
        DeleteAssessment:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /assessments/{assessmentId}
            Method: DELETE
  RetrieveBestPracticeFindingsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.12
      CodeUri: ../backend/src/api/retrieve_best_practice_findings/app
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource: !Ref DynamoDBArn
      Events:
        RetrieveBestPracticeFindings:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /assessments/{assessmentId}/best-practices/{bestPracticeName}
            Method: GET
  RetrieveFindingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.12
      CodeUri: ../backend/src/api/retrieve_finding/app
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource: !Ref DynamoDBArn
      Events:
        RetrieveBestPractice:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /assessments/{assessmentId}/findings/{findingId}
            Method: GET
