AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Frontend Resources

Parameters:
  Owner:
    Type: String
  Project:
    Type: String
  ParentStackName:
    Type: String
  Repository:
    Type: String
  ApiEndpoint:
    Type: String
  UserPoolId:
    Type: String
  IdentityPoolId:
    Type: String
  UserPoolClientId:
    Type: String

Resources:
  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: !Sub '${ParentStackName}-frontend'
      AccessToken: !Sub '{{resolve:secretsmanager:${ParentStackName}-github:SecretString}}'
      Repository: !Ref Repository
      Platform: WEB
      EnvironmentVariables:
        - Name: AMPLIFY_DIFF_DEPLOY
          Value: false
        - Name: VITE_API_URL
          Value: !Ref ApiEndpoint
        - Name: VITE_USER_POOL_ID
          Value: !Ref UserPoolId
        - Name: VITE_IDENTITY_POOL_ID
          Value: !Ref IdentityPoolId
        - Name: VITE_APP_CLIENT_ID
          Value: !Ref UserPoolClientId
      CustomRules:
        - Target: '/index.html'
          Source: '/<*>'
          Status: 404-200
        - Target: '/index.html'
          Source: '</^[^.]+$|\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>'
          Status: 200
      BuildSpec: |
        version: 1
        applications:
          - frontend:
              phases:
                preBuild:
                  commands:
                    - npm ci --cache .npm --prefer-offline
                build:
                  commands:
                    - npm run build:webui
              artifacts:
                baseDirectory: dist/webui
                files:
                  - '**/*'
              cache:
                paths:
                  - .npm/**/*
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner
        - Key: Name
          Value: AmplifyApp
  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      BranchName: 'main'
      Stage: PRODUCTION
      EnableAutoBuild: True
      Framework: React
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner
        - Key: Name
          Value: AmplifyBranch
Outputs:
  Endpoint:
    Description: Web UI endpoint
    Value: !GetAtt AmplifyApp.DefaultDomain
