AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Scanning Tools

Parameters:
  Owner:
    Type: String
  Project:
    Type: String
  ParentStackName:
    Type: String
  S3BucketName:
    Type: String

Resources:
  DefaultAssessmentRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !GetAtt ProwlerTaskRole.Arn
            Action: "sts:AssumeRole"
          - Effect: Allow
            Principal:
              AWS: !GetAtt CloudCustodianTaskRole.Arn
            Action: "sts:AssumeRole"
          - Effect: Allow
            Principal:
              AWS: !GetAtt CloudSploitTaskRole.Arn
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: ECSTaskPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: AllowMoreReadOnly
                Effect: Allow
                Action:
                  - account:Get*
                  - aoss:ListCollections
                  - appstream:Describe*
                  - appstream:List*
                  - auditmanager:GetSettings
                  - backup:List*
                  - backup:Get*
                  - bedrock:List*
                  - bedrock:Get*
                  - cloudtrail:GetInsightSelectors
                  - codeartifact:List*
                  - codebuild:BatchGet*
                  - codebuild:ListReportGroups
                  - cognito-idp:GetUserPoolMfaConfig
                  - compute-optimizer:GetRecommendationSummaries
                  - devops-guru:ListNotificationChannels
                  - dlm:Get*
                  - drs:Describe*
                  - ds:Get*
                  - ds:Describe*
                  - ds:List*
                  - dynamodb:GetResourcePolicy
                  - ec2:GetEbsDefaultKmsKeyId
                  - ec2:GetEbsEncryptionByDefault
                  - ec2:GetSnapshotBlockPublicAccessState
                  - ec2:GetInstanceMetadataDefaults
                  - ecr:Describe*
                  - ecr:GetRegistryScanningConfiguration
                  - elasticfilesystem:DescribeBackupPolicy
                  - forecast:ListForecastExportJobs
                  - geo:ListGeofenceCollections
                  - geo:DescribeGeofenceCollection
                  - geo:ListTrackers
                  - geo:DescribeTracker
                  - glue:GetConnections
                  - glue:GetSecurityConfiguration*
                  - glue:SearchTables
                  - glue:GetMLTransforms
                  - iotsitewise:DescribeDefaultEncryptionConfiguration
                  - lambda:GetFunction*
                  - logs:FilterLogEvents
                  - lightsail:GetRelationalDatabases
                  - macie2:GetMacieSession
                  - macie2:GetAutomatedDiscoveryConfiguration
                  - proton:ListEnvironmentTemplates
                  - proton:GetEnvironmentTemplate
                  - s3:GetAccountPublicAccessBlock
                  - shield:DescribeProtection
                  - shield:GetSubscriptionState
                  - securityhub:BatchImportFindings
                  - securityhub:GetFindings
                  - servicecatalog:Describe*
                  - servicecatalog:List*
                  - ssm:GetDocument
                  - ssm-incidents:List*
                  - states:ListTagsForResource
                  - support:Describe*
                  - tag:GetTagKeys
                  - timestream:DescribeEndpoints
                  - timestream:ListDatabases
                  - voiceid:ListDomains
                  - wellarchitected:List*
                  - wisdom:ListAssistants
                Resource: "*"
              - Sid: AllowAPIGatewayReadOnly
                Effect: Allow
                Action:
                  - apigateway:GET
                Resource:
                  - arn:aws:apigateway:*::*/restapis/*
                  - arn:aws:apigateway:*::*/apis/*
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
        - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${ParentStackName}-ecs-cluster"
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner
        - Key: Name
          Value: ECSCluster
  ECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: ECSExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
  ECSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/${ParentStackName}-logs"
      RetentionInDays: 14
  ProwlerTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: ECSTaskPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource:
                  - !Sub "arn:${AWS::Partition}:s3:::${S3BucketName}/*"
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                Resource: "*"
  ProwlerTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${ParentStackName}-prowler"
      Cpu: "2048"
      Memory: "4096"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt ECSExecutionRole.Arn
      TaskRoleArn: !GetAtt ProwlerTaskRole.Arn
      ContainerDefinitions:
        - Name: prowler-container
          Image: "toniblyx/prowler:5.1.5"
          Essential: true
          Cpu: 2048
          Memory: 4096
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub "/ecs/${ParentStackName}-logs"
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: prowler
              mode: non-blocking
              max-buffer-size: 25m
          Environment:
            - Name: S3_BUCKET
              Value: !Ref S3BucketName
          EntryPoint:
            - "/bin/sh"
            - "-c"
          Command:
            - prowler
              aws
              --no-banner
              --no-color
              --output-modes
              json-ocsf
              --output-bucket-no-assume
              $S3_BUCKET
              --output-directory
              assessments/$ASSESSMENT_ID/scans/prowler
              --output-filename
              "output"
              --ignore-exit-code-3
              --role
              "$ROLE_ARN"
              $REGIONS
              --status
              FAIL MANUAL
  CloudCustodianTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: ECSTaskPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:HeadObject
                  - s3:PutObject
                Resource:
                  - !Sub "arn:${AWS::Partition}:s3:::${S3BucketName}/*"
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                Resource: "*"
  CloudCustodianTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${ParentStackName}-cloud-custodian"
      Cpu: "1024"
      Memory: "4096"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt ECSExecutionRole.Arn
      TaskRoleArn: !GetAtt CloudCustodianTaskRole.Arn
      ContainerDefinitions:
        - Name: cloud-custodian-container
          Image: 576872909007.dkr.ecr.us-west-2.amazonaws.com/wafr-automation-tool:latest
          Essential: true
          Cpu: 1024
          Memory: 4096
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub "/ecs/${ParentStackName}-logs"
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: cloud-custodian
              mode: non-blocking
              max-buffer-size: 25m
          Environment:
            - Name: S3_BUCKET
              Value: !Ref S3BucketName
          EntryPoint:
            - "/bin/bash"
            - "-c"
          Command:
            - >-
              aws s3 cp $POLICIES_URI /tmp/policies.yml
              && (eval "$(aws sts assume-role --role-arn $ROLE_ARN --role-session-name "cloud-custodian-session" --query 'Credentials.{AWS_ACCESS_KEY_ID:AccessKeyId,AWS_SECRET_ACCESS_KEY:SecretAccessKey,AWS_SESSION_TOKEN:SessionToken}' --output text | awk '{print "export AWS_ACCESS_KEY_ID="$1 "\nexport AWS_SECRET_ACCESS_KEY="$2 "\nexport AWS_SESSION_TOKEN="$3}')"
              && custodian run --output-dir /tmp/cloud-custodian /tmp/policies.yml $REGIONS)
              && aws s3 cp /tmp/cloud-custodian/ s3://$S3_BUCKET/assessments/$ASSESSMENT_ID/scans/cloud-custodian/ --recursive
  CloudSploitTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: ECSTaskPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - !Sub "arn:${AWS::Partition}:s3:::${S3BucketName}/*"
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                Resource: "*"
  CloudSploitTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${ParentStackName}-cloudsploit"
      Cpu: "1024"
      Memory: "4096"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt ECSExecutionRole.Arn
      TaskRoleArn: !GetAtt CloudSploitTaskRole.Arn
      ContainerDefinitions:
        - Name: cloudsploit-container
          Image: "576872909007.dkr.ecr.us-west-2.amazonaws.com/wafr-automation-tool/cloudsploit@sha256:14ef2534a6c0920c5efb5944eb82b1154b31af769e48886cb4d6d580c024263c"
          Essential: true
          Cpu: 1024
          Memory: 4096
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub "/ecs/${ParentStackName}-logs"
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: cloudsploit
              mode: non-blocking
              max-buffer-size: 25m
          Environment:
            - Name: S3_BUCKET
              Value: !Ref S3BucketName
          EntryPoint:
            - "/bin/bash"
            - "-c"
          Command:
            - >-
              (eval "$(aws sts assume-role --role-arn $ROLE_ARN --role-session-name "cloudsploit-session" --query 'Credentials.{AWS_ACCESS_KEY_ID:AccessKeyId,AWS_SECRET_ACCESS_KEY:SecretAccessKey,AWS_SESSION_TOKEN:SessionToken}' --output text | awk '{print "export AWS_ACCESS_KEY_ID="$1 "\nexport AWS_SECRET_ACCESS_KEY="$2 "\nexport AWS_SESSION_TOKEN="$3}')"
              && cloudsploit-scan --json=output.json --console=none --ignore-ok)
              && aws s3 cp output.json s3://$S3_BUCKET/assessments/$ASSESSMENT_ID/scans/cloudsploit/output.json
Outputs:
  DefaultAssessmentRole:
    Description: Default Assessment Role
    Value: !GetAtt DefaultAssessmentRole.Arn
  ECSCluster:
    Description: ECS Cluster
    Value: !Ref ECSCluster
  ECSExecutionRole:
    Description: ECS Execution Role
    Value: !GetAtt ECSExecutionRole.Arn
  ProwlerTaskDefinition:
    Description: Prowler Task Definition
    Value: !Ref ProwlerTaskDefinition
  ProwlerTaskRole:
    Description: Prowler Task Role
    Value: !GetAtt ProwlerTaskRole.Arn
  CloudCustodianTaskDefinition:
    Description: Cloud Custodian Task Definition
    Value: !Ref CloudCustodianTaskDefinition
  CloudCustodianTaskRole:
    Description: Cloud Custodian Task Role
    Value: !GetAtt CloudCustodianTaskRole.Arn
  CloudSploitTaskDefinition:
    Description: Cloud Sploit Task Definition
    Value: !Ref CloudSploitTaskDefinition
  CloudSploitTaskRole:
    Description: Cloud Sploit Task Role
    Value: !GetAtt CloudSploitTaskRole.Arn
