AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: State Machine

Parameters:
  Owner:
    Type: String
    Default: Antoine Berger
  Project:
    Type: String
    Default: WAFR Automation Tool
  Name:
    Type: String
    Default: state-machine
  ParentStackName:
    Type: String
  Debug:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  SharedLibsLayer:
    Type: String
  DynamoDBArn:
    Type: String
  S3BucketName:
    Type: String
  ECSCluster:
    Type: String
  ECSExecutionRole:
    Type: String
  ProwlerTaskDefinition:
    Type: String
  ProwlerTaskRole:
    Type: String
  CloudCustodianTaskDefinition:
    Type: String
  CloudCustodianTaskRole:
    Type: String
  CloudSploitTaskDefinition:
    Type: String
  CloudSploitTaskRole:
    Type: String
  Subnet:
    Type: String
  SecurityGroup:
    Type: String

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: python3.12
    Layers:
      - !Ref SharedLibsLayer
    Tags:
      Project: !Ref Project
      Owner: !Ref Owner
      Name: !Ref Name
    Environment:
      Variables:
        DEBUG: !Ref Debug
        REGION: !Ref AWS::Region
        S3_BUCKET: !Ref S3BucketName
        DDB_TABLE: !Ref DynamoDBArn

Resources:
  PreparePromptsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.12
      CodeUri: ../backend/src/state_machine/prepare_prompts/app
      Timeout: 300
      MemorySize: 512
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource:
                - !Sub "arn:${AWS::Partition}:s3:::${S3BucketName}/*"
            - Effect: Allow
              Action:
                - s3:ListBucket
              Resource:
                - !Sub "arn:${AWS::Partition}:s3:::${S3BucketName}"
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
              Resource:
                - !Ref DynamoDBArn
  InvokeLLMFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.12
      CodeUri: ../backend/src/state_machine/invoke_llm/app
      Timeout: 300
      MemorySize: 128
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource:
                - !Sub "arn:${AWS::Partition}:s3:::${S3BucketName}/*"
            - Effect: Allow
              Action:
                - s3:ListBucket
              Resource:
                - !Sub "arn:${AWS::Partition}:s3:::${S3BucketName}"
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: "*"
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
                - dynamodb:PutItem
              Resource:
                - !Ref DynamoDBArn
      Environment:
        Variables:
          AI_MODEL: claude-3-5-sonnet
  CleanupFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.12
      CodeUri: ../backend/src/state_machine/cleanup/app
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:BatchWriteItem
              Resource:
                - !Ref DynamoDBArn
            - Effect: Allow
              Action:
                - s3:DeleteObject
              Resource:
                - !Sub "arn:${AWS::Partition}:s3:::${S3BucketName}/*"
            - Effect: Allow
              Action:
                - s3:ListBucket
              Resource:
                - !Sub "arn:${AWS::Partition}:s3:::${S3BucketName}"
  PrepareCustodianFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.12
      CodeUri: ../backend/src/state_machine/prepare_custodian/app
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource:
                - !Sub "arn:${AWS::Partition}:s3:::${S3BucketName}/*"
  StateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub "${ParentStackName}-StateMachine"
      Tags:
        Project: !Ref Project
        Owner: !Ref Owner
        Name: !Ref Name
      Policies:
        - Statement:
            Effect: Allow
            Action: states:StartExecution
            Resource:
              - !Sub "arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${ParentStackName}-StateMachine"
        - Statement:
            Effect: Allow
            Action: ecs:RunTask
            Resource:
              - !Sub "arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:task-definition/${ParentStackName}-prowler:*"
              - !Sub "arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:task-definition/${ParentStackName}-cloud-custodian:*"
              - !Sub "arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:task-definition/${ParentStackName}-cloudsploit:*"
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:UpdateItem
              - dynamodb:PutItem
            Resource:
              - !Ref DynamoDBArn
        - Statement:
            Effect: Allow
            Action: iam:PassRole
            Resource:
              - !Ref ECSExecutionRole
              - !Ref ProwlerTaskRole
              - !Ref CloudCustodianTaskRole
              - !Ref CloudSploitTaskRole
        - Statement:
            Effect: Allow
            Action:
              - events:PutRule
              - events:PutTargets
              - events:DescribeRule
              - events:DeleteRule
              - events:RemoveTargets
            Resource: "*"
        - Statement:
            Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource:
              - !GetAtt PreparePromptsFunction.Arn
              - !GetAtt InvokeLLMFunction.Arn
              - !GetAtt CleanupFunction.Arn
              - !GetAtt PrepareCustodianFunction.Arn
      Definition:
        Comment: "State Machine for WAFR Automation Tool"
        QueryLanguage: JSONata
        StartAt: CreateAssessment
        States:
          CreateAssessment:
            Type: Task
            Resource: arn:aws:states:::dynamodb:putItem
            Arguments:
              TableName: !Ref DynamoDBArn
              Item:
                PK:
                  S: "ASSESSMENT"
                SK:
                  S: "{% $states.input.assessment_id %}"
                name:
                  S: "{% $states.input.name %}"
                role:
                  S: "{% $states.input.role %}"
                step:
                  S: "Start the scanning process"
            Assign:
              assessment_id: "{% $states.input.assessment_id %}"
              role: "{% $states.input.role %}"
            Next: ScanningTools
            Catch:
              - ErrorEquals:
                  - States.ALL
                Next: CleanupOnError
                Output:
                  assessment_id: "{% $states.input.assessment_id %}"
                  error: "{% $states.errorOutput %}"
          ScanningTools:
            Type: Parallel
            Branches:
              - StartAt: ProwlerScan
                States:
                  ProwlerScan:
                    Type: Task
                    Resource: arn:aws:states:::ecs:runTask.sync
                    Arguments:
                      LaunchType: FARGATE
                      Cluster: !Ref ECSCluster
                      TaskDefinition: !Ref ProwlerTaskDefinition
                      NetworkConfiguration:
                        AwsvpcConfiguration:
                          Subnets:
                            - !Ref Subnet
                          SecurityGroups:
                            - !Ref SecurityGroup
                          AssignPublicIp: ENABLED
                      Overrides:
                        ContainerOverrides:
                          - Name: prowler-container
                            Environment:
                              - Name: ASSESSMENT_ID
                                Value: "{% $assessment_id %}"
                              - Name: ROLE
                                Value: "{% $role %}"
                    End: true
              - StartAt: PrepareCustodian
                States:
                  PrepareCustodian:
                    Type: Task
                    Resource: !GetAtt PrepareCustodianFunction.Arn
                    Next: CloudCustodianScan
                  CloudCustodianScan:
                    Type: Task
                    Resource: arn:aws:states:::ecs:runTask.sync
                    Arguments:
                      LaunchType: FARGATE
                      Cluster: !Ref ECSCluster
                      TaskDefinition: !Ref CloudCustodianTaskDefinition
                      NetworkConfiguration:
                        AwsvpcConfiguration:
                          Subnets:
                            - !Ref Subnet
                          SecurityGroups:
                            - !Ref SecurityGroup
                          AssignPublicIp: ENABLED
                      Overrides:
                        ContainerOverrides:
                          - Name: cloud-custodian-container
                            Environment:
                              - Name: ASSESSMENT_ID
                                Value: "{% $assessment_id %}"
                              - Name: POLICIES_URI
                                Value: "{% $states.input %}"
                              - Name: ROLE
                                Value: "{% $role %}"
                    End: true
              - StartAt: CloudSploitScan
                States:
                  CloudSploitScan:
                    Type: Task
                    Resource: arn:aws:states:::ecs:runTask.sync
                    Arguments:
                      LaunchType: FARGATE
                      Cluster: !Ref ECSCluster
                      TaskDefinition: !Ref CloudSploitTaskDefinition
                      NetworkConfiguration:
                        AwsvpcConfiguration:
                          Subnets:
                            - !Ref Subnet
                          SecurityGroups:
                            - !Ref SecurityGroup
                          AssignPublicIp: ENABLED
                      Overrides:
                        ContainerOverrides:
                          - Name: cloudsploit-container
                            Environment:
                              - Name: ASSESSMENT_ID
                                Value: "{% $assessment_id %}"
                              - Name: ROLE
                                Value: "{% $role %}"
                    End: true
            Next: PreparePromptsUpdateStep
            Catch:
              - ErrorEquals:
                  - States.ALL
                Next: CleanupOnError
                Output:
                  assessment_id: "{% $assessment_id %}"
                  error: "{% $states.errorOutput %}"
          PreparePromptsUpdateStep:
            Type: Task
            Resource: arn:aws:states:::dynamodb:updateItem
            Arguments:
              TableName: !Ref DynamoDBArn
              Key:
                PK:
                  S: "ASSESSMENT"
                SK:
                  S: "{% $assessment_id %}"
              UpdateExpression: SET step = :newStep
              ExpressionAttributeValues:
                ":newStep":
                  S: "Prepare all prompts"
            Next: Prepare Prompts
            Catch:
              - ErrorEquals:
                  - States.ALL
                Next: CleanupOnError
                Output:
                  assessment_id: "{% $assessment_id %}"
                  error: "{% $states.errorOutput %}"
          Prepare Prompts:
            Type: Parallel
            Branches:
              - StartAt: Prepare Prowler Prompts
                States:
                  Prepare Prowler Prompts:
                    Type: Task
                    Resource: !GetAtt PreparePromptsFunction.Arn
                    Arguments:
                      assessment_id: "{% $assessment_id %}"
                      scanning_tool: "prowler"
                    End: true
              - StartAt: Prepare Cloud Custodian Prompts
                States:
                  Prepare Cloud Custodian Prompts:
                    Type: Task
                    Resource: !GetAtt PreparePromptsFunction.Arn
                    Arguments:
                      assessment_id: "{% $assessment_id %}"
                      scanning_tool: "cloud-custodian"
                    End: true
              - StartAt: Prepare CloudSploit Prompts
                States:
                  Prepare CloudSploit Prompts:
                    Type: Task
                    Resource: !GetAtt PreparePromptsFunction.Arn
                    Arguments:
                      assessment_id: "{% $assessment_id %}"
                      scanning_tool: "cloudsploit"
                    End: true
            Next: InvokeLLMUpdateStep
            Output: "{% $spread($states.result) %}"
            Catch:
              - ErrorEquals:
                  - States.ALL
                Next: CleanupOnError
                Output:
                  assessment_id: "{% $assessment_id %}"
                  error: "{% $states.errorOutput %}"
          InvokeLLMUpdateStep:
            Type: Task
            Resource: arn:aws:states:::dynamodb:updateItem
            Arguments:
              TableName: !Ref DynamoDBArn
              Key:
                PK:
                  S: "ASSESSMENT"
                SK:
                  S: "{% $assessment_id %}"
              UpdateExpression: SET step = :newStep
              ExpressionAttributeValues:
                ":newStep":
                  S: "Invoke LLM"
            Next: PromptMap
            Output: "{% $states.input %}"
            Catch:
              - ErrorEquals:
                  - States.ALL
                Next: CleanupOnError
                Output:
                  assessment_id: "{% $assessment_id %}"
                  error: "{% $states.errorOutput %}"
          PromptMap:
            Type: Map
            ItemProcessor:
              ProcessorConfig:
                Mode: INLINE
              StartAt: InvokeLLM
              States:
                InvokeLLM:
                  Type: Task
                  Resource: !GetAtt InvokeLLMFunction.Arn
                  Arguments:
                    assessment_id: "{% $assessment_id %}"
                    prompt_uri: "{% $states.input %}"
                  End: true
                  Retry:
                    - ErrorEquals:
                        - States.TaskFailed
                      BackoffRate: 2
                      IntervalSeconds: 1
                      MaxAttempts: 3
            Next: FinishUpdateStep
            Catch:
              - ErrorEquals:
                  - States.ALL
                Next: CleanupOnError
                Output:
                  assessment_id: "{% $assessment_id %}"
                  error: "{% $states.errorOutput %}"
          FinishUpdateStep:
            Type: Task
            Resource: arn:aws:states:::dynamodb:updateItem
            Arguments:
              TableName: !Ref DynamoDBArn
              Key:
                PK:
                  S: "ASSESSMENT"
                SK:
                  S: "{% $assessment_id %}"
              UpdateExpression: SET step = :newStep
              ExpressionAttributeValues:
                ":newStep":
                  S: "Finish"
            Next: Cleanup
            Catch:
              - ErrorEquals:
                  - States.ALL
                Next: CleanupOnError
                Output:
                  assessment_id: "{% $assessment_id %}"
                  error: "{% $states.errorOutput %}"
          Cleanup:
            Type: Task
            Resource: !GetAtt CleanupFunction.Arn
            Arguments:
              assessment_id: "{% $assessment_id %}"
            End: true
          CleanupOnError:
            Type: Task
            Resource: !GetAtt CleanupFunction.Arn
            End: true

Outputs:
  StateMachineArn:
    Description: State Machine Arn
    Value: !Ref StateMachine
