AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: State Machine

Parameters:
  Owner:
    Type: String
    Default: Antoine Berger
  Project:
    Type: String
    Default: WAFR Automation Tool
  Name:
    Type: String
    Default: wafr-automation-tool
  DynamoDBArn:
    Type: String
  S3BucketName:
    Type: String
  ParentStackName:
    Type: String
  SharedLibsLayer:
    Type: String

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: python3.12
    Layers:
      - !Ref SharedLibsLayer
    Tags:
      Project: !Ref Project
      Owner: !Ref Owner
      Name: !Ref Name
    Environment:
      Variables:
        S3_BUCKET: !Ref S3BucketName
        DYNAMODB_TABLE: !Ref DynamoDBArn

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner
        - Key: Name
          Value: !Ref Name
  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Sub ${AWS::Region}a
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner
        - Key: Name
          Value: !Ref Name
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner
        - Key: Name
          Value: !Ref Name
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner
        - Key: Name
          Value: !Ref Name
  Route:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet
      RouteTableId: !Ref RouteTable
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ECS
      VpcId: !Ref VPC
      SecurityGroupEgress:
        - IpProtocol: "tcp"
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner
        - Key: Name
          Value: !Ref Name
  PreparePromptsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.12
      CodeUri: ../backend/src/state_machine/prepare_prompts/app
      Timeout: 300
      MemorySize: 512
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource:
                - !Sub "arn:${AWS::Partition}:s3:::${S3BucketName}/*"
            - Effect: Allow
              Action:
                - s3:ListBucket
              Resource:
                - !Sub "arn:${AWS::Partition}:s3:::${S3BucketName}"
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
              Resource:
                - !Ref DynamoDBArn
  InvokeLLMFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.12
      CodeUri: ../backend/src/state_machine/invoke_llm/app
      Timeout: 300
      MemorySize: 128
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource:
                - !Sub "arn:${AWS::Partition}:s3:::${S3BucketName}/*"
            - Effect: Allow
              Action:
                - s3:ListBucket
              Resource:
                - !Sub "arn:${AWS::Partition}:s3:::${S3BucketName}"
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:RetrieveAndGenerate
              Resource: "*"
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
                - dynamodb:PutItem
              Resource:
                - !Ref DynamoDBArn
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${ParentStackName}-ecs-cluster"
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner
        - Key: Name
          Value: !Ref Name
  ECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: ECSExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: ECSTaskPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource:
                  - !Sub "arn:${AWS::Partition}:s3:::${S3BucketName}/*"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
        - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
  ECSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/${ParentStackName}-logs"
      RetentionInDays: 14
  ProwlerTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${ParentStackName}-prowler"
      Cpu: "1024"
      Memory: "4096"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt ECSExecutionRole.Arn
      TaskRoleArn: !GetAtt ECSTaskRole.Arn
      ContainerDefinitions:
        - Name: prowler-container
          Image: "toniblyx/prowler:5.1.5"
          Essential: true
          Cpu: 1024
          Memory: 4096
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub "/ecs/${ParentStackName}-logs"
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: prowler
          Command:
            - aws
            - --output-modes
            - json-ocsf
            - --output-bucket
            - !Ref S3BucketName
            - --output-directory
            - scan/prowler
            - --output-filename
            - "prowler-output-$ID"
            - --ignore-exit-code-3
  StateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub "${ParentStackName}-StateMachine"
      Tags:
        Project: !Ref Project
        Owner: !Ref Owner
        Name: !Ref Name
      Policies:
        - Statement:
            Effect: Allow
            Action: states:StartExecution
            Resource:
              - !Sub "arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${ParentStackName}-StateMachine"
        - Statement:
            Effect: Allow
            Action: ecs:RunTask
            Resource:
              - !Sub "arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:task-definition/${ParentStackName}-prowler:*"
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:UpdateItem
              - dynamodb:PutItem
            Resource:
              - !Ref DynamoDBArn
        - Statement:
            Effect: Allow
            Action: iam:PassRole
            Resource:
              - !GetAtt ECSExecutionRole.Arn
              - !GetAtt ECSTaskRole.Arn
        - Statement:
            Effect: Allow
            Action:
              - events:PutRule
              - events:PutTargets
              - events:DescribeRule
              - events:DeleteRule
              - events:RemoveTargets
            Resource: "*"
        - Statement:
            Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource:
              - !GetAtt PreparePromptsFunction.Arn
              - !GetAtt InvokeLLMFunction.Arn
      Definition:
        Comment: "State Machine for WAFR Automation Tool"
        QueryLanguage: JSONata
        StartAt: CreateItem
        States:
          CreateItem:
            Type: Task
            Resource: arn:aws:states:::dynamodb:putItem
            Arguments:
              TableName: !Ref DynamoDBArn
              Item:
                id:
                  S: "{% $states.input.id %}"
                finding_id:
                  S: "0"
                name:
                  S: "{% $states.input.name %}"
                role:
                  S: "{% $states.input.role %}"
                step:
                  S: "0"
            Assign:
              id: "{% $states.input.id %}"
              role: "{% $states.input.role %}"
            Next: ScanningTools
          ScanningTools:
            Type: Parallel
            Branches:
              - StartAt: ProwlerScan
                States:
                  ProwlerScan:
                    Type: Task
                    Resource: arn:aws:states:::ecs:runTask.sync
                    Arguments:
                      LaunchType: FARGATE
                      Cluster: !Ref ECSCluster
                      TaskDefinition: !Ref ProwlerTaskDefinition
                      NetworkConfiguration:
                        AwsvpcConfiguration:
                          Subnets:
                            - !Ref Subnet
                          SecurityGroups:
                            - !Ref SecurityGroup
                          AssignPublicIp: ENABLED
                      Overrides:
                        ContainerOverrides:
                          - Name: prowler-container
                            Environment:
                              - Name: ID
                                Value: "{% $id %}"
                              - Name: ROLE
                                Value: "{% $role %}"
                    End: true
            Next: UpdateItem
          UpdateItem:
            Type: Task
            Resource: arn:aws:states:::dynamodb:updateItem
            Arguments:
              TableName: !Ref DynamoDBArn
              Key:
                id:
                  S: "{% $id %}"
                finding_id:
                  S: "0"
              UpdateExpression: SET step = :newStep
              ExpressionAttributeValues:
                ":newStep":
                  N: "1"
            Next: PreparePrompt
          PreparePrompt:
            Type: Task
            Resource: !GetAtt PreparePromptsFunction.Arn
            Arguments:
              id: "{% $id %}"
            Next: BedrockMap
          BedrockMap:
            Type: Map
            ItemProcessor:
              ProcessorConfig:
                Mode: INLINE
              StartAt: InvokeLLM
              States:
                InvokeLLM:
                  Type: Task
                  Resource: !GetAtt InvokeLLMFunction.Arn
                  Arguments:
                    id: "{% $id %}"
                    prompt_uri: "{% $states.input %}"
                  End: true
            End: true
Outputs:
  StateMachineArn:
    Description: State Machine Arn
    Value: !Ref StateMachine
