AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: State Machine

Parameters:
  Owner:
    Type: String
    Default: Antoine Berger
  Project:
    Type: String
    Default: WAFR Automation Tool
  Name:
    Type: String
    Default: wafr-automation-tool
  DynamoDBArn:
    Type: String
  ParentStackName:
    Type: String

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner
        - Key: Name
          Value: !Ref Name
  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Sub ${AWS::Region}a
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner
        - Key: Name
          Value: !Ref Name
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner
        - Key: Name
          Value: !Ref Name
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner
        - Key: Name
          Value: !Ref Name
  Route:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet
      RouteTableId: !Ref RouteTable
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ECS
      VpcId: !Ref VPC
      SecurityGroupEgress:
        - IpProtocol: "tcp"
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner
        - Key: Name
          Value: !Ref Name
  PreparePromptFunction:
    Type: AWS::Serverless::Function
    Properties:
      Tags:
        Owner: !Ref Owner
        Project: !Ref Project
        Name: !Ref Name
      Handler: main.lambda_handler
      Runtime: python3.13
      CodeUri: ../backend/src/state_machine/prepare_prompt
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${AWS::StackName}-ecs-cluster"
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner
        - Key: Name
          Value: !Ref Name
  ECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: ECSExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
  ProwlerECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "prowler-ecr"
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner
        - Key: Name
          Value: !Ref Name
  ProwlerTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${AWS::StackName}-prowler"
      Cpu: "256"
      Memory: "1024"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt ECSExecutionRole.Arn
      ContainerDefinitions:
        - Name: prowler-container
          Image: !Sub "${ProwlerECR.RepositoryUri}:latest"
          Essential: true
          Cpu: 256
          Memory: 1024
  StateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub "${AWS::StackName}-StateMachine"
      Tags:
        Project: !Ref Project
        Owner: !Ref Owner
        Name: !Ref Name
      Policies:
        - Statement:
            Effect: Allow
            Action: states:StartExecution
            Resource:
              - !Sub "arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${AWS::StackName}-StateMachine"
        - Statement:
            Effect: Allow
            Action: ecs:RunTask
            Resource:
              - !Sub "arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:task-definition/${AWS::StackName}-prowler:*"
        - Statement:
            Effect: Allow
            Action: bedrock:InvokeModel
            Resource: "*"
        - Statement:
            Effect: Allow
            Action: dynamodb:UpdateItem
            Resource:
              - !Ref DynamoDBArn
        - Statement:
            Effect: Allow
            Action: iam:PassRole
            Resource:
              - !GetAtt ECSExecutionRole.Arn
        - Statement:
            Effect: Allow
            Action:
              - events:PutRule
              - events:PutTargets
              - events:DescribeRule
              - events:DeleteRule
              - events:RemoveTargets
            Resource: "*"
      Definition:
        Comment: "State Machine for WAFR Automation Tool"
        QueryLanguage: JSONata
        StartAt: ScanningTools
        States:
          ScanningTools:
            Type: Parallel
            Branches:
              - StartAt: ProwlerScan
                States:
                  ProwlerScan:
                    Type: Task
                    Resource: arn:aws:states:::ecs:runTask.sync
                    Output: "{% $states.result %}"
                    Arguments:
                      LaunchType: FARGATE
                      Cluster: !Ref ECSCluster
                      TaskDefinition: !Ref ProwlerTaskDefinition
                    End: true
            Next: PreparePrompt
          PreparePrompt:
            Type: Task
            Resource: !GetAtt PreparePromptFunction.Arn
            Output: "{% $states.result.Payload %}"
            Arguments:
              Payload: "{% $states.input %}"
            Next: InvokeLLM
          InvokeLLM:
            Type: Task
            Resource: arn:aws:states:::bedrock:invokeModel
            Output: "{% $states.result.Payload %}"
            Arguments:
              ModelId: >-
                arn:aws:bedrock:us-west-2::foundation-model/anthropic.claude-3-5-haiku-20241022-v1:0
              Body:
                anthropic_version: bedrock-2023-05-31
                max_tokens: 200
                messages:
                  - role: user
                    content:
                      - type: text
                        text: "{% $states.input %}"
            Next: StoreResults
          StoreResults:
            Type: Task
            Resource: arn:aws:states:::dynamodb:updateItem
            Arguments:
              TableName: !Ref DynamoDBArn
              Key:
                Column:
                  S: MyEntry
              UpdateExpression: SET MyKey = :myValueRef
              ExpressionAttributeValues:
                ":myValueRef":
                  S: MyValue
            End: true

Outputs:
  StateMachineArn:
    Description: State Machine Arn
    Value: !Ref StateMachine
