from enum import StrEnum


class Steps(StrEnum):
    SCANNING_STARTED = "SCANNING_STARTED"
    PREPARING_PROMPTS = "PREPARING_PROMPTS"
    INVOKING_LLM = "INVOKING_LLM"
    FINISHED = "FINISHED"
    ERRORED = "ERRORED"
